###
POST http://127.0.0.1:8000/cats/ HTTP/1.1
content-type: application/json
Authorization: Token fe5fcd7eef899564ef3c6a74b7f5f855bc74f5b2

{
    "name": "whitecat",
    "color": "White",
    "birth_year": 2009,
    "owner": 1,
    "achievements": [
        {"achievement_name": "поймал мышку"}
    ]
    
}

###
GET http://127.0.0.1:8000/cats/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4ODI1OTU2LCJpYXQiOjE3Njg3Mzk1NTYsImp0aSI6IjE2ZTM4MzgyNGM1MTRlZGZhYmYyN2ExZTJiZDZlNDBmIiwidXNlcl9pZCI6IjIifQ.VXa5eK3AXF4d3sg4GiaxZHQTiYk6guCre7O4pfIN_vI

###
GET http://127.0.0.1:8000/cats/recent-white-cats/
Authorization: Token fe5fcd7eef899564ef3c6a74b7f5f855bc74f5b2

###
GET http://127.0.0.1:8000/mycats/3
Authorization: Token fe5fcd7eef899564ef3c6a74b7f5f855bc74f5b2

###
GET http://127.0.0.1:8000/cats
Authorization: Token fe5fcd7eef899564ef3c6a74b7f5f855bc74f5b2



###
PATCH http://127.0.0.1:8000/cats/1/ HTTP/1.1
content-type: application/json
Authorization: Token fe5fcd7eef899564ef3c6a74b7f5f855bc74f5b2

{
    "name": "blackcat1",
    "color": "#228B22",
    "birth_year": 2009
}
###
GET http://127.0.0.1:8000/owners/
###
POST http://127.0.0.1:8000/owners/ HTTP/1.1
content-type: application/json
Authorization: Token fe5fcd7eef899564ef3c6a74b7f5f855bc74f5b2

{
    "first_name": "Иван",
    "last_name": "Иванов"
}

### 
POST http://127.0.0.1:8000/cats/ HTTP/1.1
content-type: application/json
Authorization: Token fe5fcd7eef899564ef3c6a74b7f5f855bc74f5b2


{
    "name": "Барсик",
    "color": "White",
    "birth_year": 2017,
    "owner": 1,
    "achievements": [
        {"name": "поймал мышку"},
        {"name": "разбил вазу"}
    ]
} 


{
    "text": "Текст для моего поста",
    "author": 1,
    "tag": [
        {"name": "хобби"},
        {"name": "личное"}
        ]
} 


### 
POST http://127.0.0.1:8000/api-token-auth/ HTTP/1.1
content-type: application/json

{
    "username": "idotsenko",
    "password": "korgAX3GHSPA"
}

### 
POST http://127.0.0.1:8000/auth/users/ HTTP/1.1
content-type: application/json

{
    "username": "test",
    "password": "testtest1234"
}
### 
POST http://127.0.0.1:8000/auth/jwt/create/ HTTP/1.1
content-type: application/json

{
    "username": "test",
    "password": "testtest1234"
}


# {
#   "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2ODgyNTk1NiwiaWF0IjoxNzY4NzM5NTU2LCJqdGkiOiI0YTc0ZmQyNzllNzY0MjI4YmFjZWJiMmI2ZjI4ZDNjYiIsInVzZXJfaWQiOiIyIn0.vvBGNk0WJEwzg_J2Gt73KR66cbqaWe4zr6eWU62rCo8",
#   "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4ODI1OTU2LCJpYXQiOjE3Njg3Mzk1NTYsImp0aSI6IjE2ZTM4MzgyNGM1MTRlZGZhYmYyN2ExZTJiZDZlNDBmIiwidXNlcl9pZCI6IjIifQ.VXa5eK3AXF4d3sg4GiaxZHQTiYk6guCre7O4pfIN_vI"
# }