###
POST http://127.0.0.1:8000/cats/ HTTP/1.1
content-type: application/json

{
    "name": "blackcat",
    "color": "#228B22",
    "birth_year": 2009,
    "owner": 1,
    "achievements": [
        {"achievement_name": "поймал мышку"}
    ]
    
}

###
GET http://127.0.0.1:8000/cats/

###
PATCH http://127.0.0.1:8000/cats/1/ HTTP/1.1
content-type: application/json

{
    "name": "blackcat1",
    "color": "#228B22",
    "birth_year": 2009
}
###
GET http://127.0.0.1:8000/owners/
###
POST http://127.0.0.1:8000/owners/ HTTP/1.1
content-type: application/json

{
    "first_name": "Иван",
    "last_name": "Иванов"
}

### 
POST http://127.0.0.1:8000/cats/ HTTP/1.1
content-type: application/json

{
    "name": "Барсик",
    "color": "White",
    "birth_year": 2017,
    "owner": 1,
    "achievements": [
        {"name": "поймал мышку"},
        {"name": "разбил вазу"}
    ]
} 

###
GET https://9cc2f663-486e-4680-8181-84edc9371f8b.serverhub.praktikum-services.ru/posts/


###
POST https://9cc2f663-486e-4680-8181-84edc9371f8b.serverhub.praktikum-services.ru/posts/
content-type: application/json


{
    "text": "Текст для моего поста",
    "author": 1,
    "tag": [
        {"name": "хобби"},
        {"name": "личное"}
        ]
} 